services:
  db:
    image: pgvector/pgvector:pg17
    container_name: rss_db
    environment:
      POSTGRES_USER: rss_user
      POSTGRES_PASSWORD: rss_password
      POSTGRES_DB: rss_db
    ports:
      - "5432:5432"
    volumes:
      - rss_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  rss_db_data:
