[build]
builder = "NIXPACKS"

[deploy]
preDeploy = "npx drizzle-kit migrate"
startCommand = "npm run start -- -p $PORT"
healthcheckPath = "/api/ping"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
